// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function isValidInputString(input) {
  switch (input) {
    case "bottom left" :
    case "bottom middle" :
    case "bottom right" :
    case "middle left" :
    case "middle middle" :
    case "middle right" :
    case "top left" :
    case "top middle" :
    case "top right" :
        return true;
    default:
      return false;
  }
}

function gatherInput(input) {
  switch (input) {
    case "bottom left" :
        return /* BottomLeft */6;
    case "bottom middle" :
        return /* BottomMiddle */7;
    case "bottom right" :
        return /* BottomRight */8;
    case "middle left" :
        return /* MiddleLeft */3;
    case "middle middle" :
        return /* MiddleMiddle */4;
    case "middle right" :
        return /* MiddleRight */5;
    case "top left" :
        return /* TopLeft */0;
    case "top middle" :
        return /* TopMiddle */1;
    case "top right" :
        return /* TopRight */2;
    default:
      return /* BottomRight */8;
  }
}

exports.isValidInputString = isValidInputString;
exports.gatherInput = gatherInput;
/* No side effect */
